//! libseccomp-friendly C header emitter.
//!
//! Output is a self-contained header. The caller pulls it in,
//! initializes a context with `seccomp_init(SCMP_ACT_ERRNO(1))`, and
//! iterates `sandprint_syscalls[]` adding each entry with
//! `seccomp_rule_add(ctx, SCMP_ACT_ALLOW, syscalls[i], 0)`.

use std::fmt::Write;

use super::Trace;

pub fn emit(trace: &Trace) -> String {
    let names = trace.unique_syscall_names();
    let mut s = String::new();
    let _ = writeln!(s, "/* Generated by sandprint. Do not edit. */");
    let _ = writeln!(s, "#ifndef SANDPRINT_PROFILE_H");
    let _ = writeln!(s, "#define SANDPRINT_PROFILE_H");
    let _ = writeln!(s);
    let _ = writeln!(s, "#include <seccomp.h>");
    let _ = writeln!(s);
    let _ = writeln!(s, "static const int sandprint_syscalls[] = {{");
    for n in &names {
        let _ = writeln!(s, "    SCMP_SYS({n}),");
    }
    let _ = writeln!(s, "}};");
    let _ = writeln!(s);
    let _ = writeln!(s, "#define SANDPRINT_NUM_SYSCALLS {}", names.len());
    let _ = writeln!(s);
    let _ = writeln!(s, "#endif /* SANDPRINT_PROFILE_H */");
    s
}
